name: Send Weather Reports

on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

jobs:
  send-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Send weather reports
        run: |
          python send_reports.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}